FORMAT: 1A
HOST: https://apidev15.pdffiller.com

# Documentation V2

Try to make new easier way to do api-docs



## Template collection [/v2/templates]
  
### Retrieves a list of uploaded templates [GET /v2/templates{?datefrom}{?dateto}]
+ Request (application/x-www-form-urlencoded)
    + Headers
    
            Authorization: Bearer
            
    + Attributes
        + folder_id (number, optional) - Filter by folder
            + Default: 0
        + date_from (string, optional) - Filter by date from
        + date_to (string, optional) - Filter by date to

    + Body

            {
                "folder_id": 0,
                "date_from": "date",
                "date_to": "date"
            }
            
+ Parameters
    + datefrom: string (string, optional) - Filter by date from
    + dateto: string (string, optional) - Filter by date to
    
+ Response 200 (application/json)

    Success - information about document template

    + Attributes (Template_list)
    
+ Response 400 (application/json)

    Bad request - request validation error

    + Attributes (Error_response)
    
+ Response 401 (application/json)

    Unauthorized - access application is invalid or doesn't have access privileges to requested resource

    + Attributes (Error_response)

+ Response 403 (application/json)

    Forbidden - access to resource forbidden for this application

    + Attributes (Error_response)

+ Response 500 (application/json)

    Server error

    + Attributes (Error_response)

### Creates a new document template by uploading file in form-data [POST /v2/templates]
+ Request (multipart/form-data; boundary={boundary value})
    
    + Headers
    
            Authorization: Bearer
    
    + Attributes
        + file (string, required) - File content for upload
        + folder_id (number, optional)
            + Default : 0
            
    + Body 
      
            --{boundary value}
            Content-Disposition: form-data; name='file'; filename='123456.docx'
            Content-Type: text/plain (according to the type of the uploaded file)
              
            UEsDBBQABgAIAAAAIQAJJIeCgQEAAI4FAAATAAgCW0NvbnRlbnRfVHlwZXNdLnhtbCCiBAIooAAC
            AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
            AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
            AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
            AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
            AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
            AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
            AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
            AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
            AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC0
            lE1Pg0AQhu8m/geyVwPbejDGlPag9ahNrPG8LkPZyH5kZ/v17x1KS6qhpVq9kMAy7/vMCzOD0UqX
            0QI8KmtS1k96LAIjbabMLGWv08f4lkUYhMlEaQ2kbA3IRsPLi8F07QAjqjaYsiIEd8c5ygK0wMQ6
            MHSSW69FoFs/407IDzEDft3r3XBpTQAT4lBpsOHgAXIxL0M0XtHjmsRDiSy6r1+svFImnCuVFIFI
            +cJk31zirUNClZt3sFAOrwiD8VaH6uSwwbbumaLxKoNoInx4Epow+NL6jGdWzjX1kByXaeG0ea4k
            NPWVmvNWAiJlrsukOdFCmR3/QQ4M6xLw7ylq3RPt31QoxnkOkj52dx4a46rppLbYq+12gxAopFNM
            vv6CcVfouFXuRFjC+8u/UeyJd4LkNBpT8V7CCYn/MIxGuhMi0LwD31z7Z3NsZI5Z0mRMvHVI+8P/
            ou3dgqiqYxo5Bz4oaFZE24g1jrR7zu4Pqu2WQdbizTfbdPgJAAD//wMAUEsDBBQABgAIAAAAIQAe
            kRq38wAAAE4CAAALAAgCX3JlbHMvLnJlbHMgogQCKKAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
            AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
            AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
            AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
            AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
            AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
            AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
            AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
            AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
            AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAjJLbSgNBDIbvBd9hyH032woi0tneSKF3
            IusDhJnsAXcOzKTavr2jILpQ217m9OfLT9abg5vUO6c8Bq9hWdWg2JtgR99reG23iwdQWchbmoJn
            DUfOsGlub9YvPJGUoTyMMaui4rOGQSQ+ImYzsKNchci+VLqQHEkJU4+RzBv1jKu6vsf0VwOamaba
            WQ1pZ+9AtcdYNl/WDl03Gn4KZu/Yy4kVyAdhb9kuYipsScZyjWop9SwabDDPJZ2RYqwKNuBpotX1
            RP9fi46FLAmhCYnP83x1nANaXg902aJ5x687HyFZLBZ9e/tDg7MvaD4BAAD//wMAUEsDBBQABgAI
            AAAAIQB8O5c5IgEAALkDAAAcAAgBd29yZC9fcmVscy9kb2N1bWVudC54bWwucmVscyCiBAEooAAB
            AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
            AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
            AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
            AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
            AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKyTTU+EMBCG7yb+B9K7FFZdjdmyFzXZq67x3C1T
            aISWdMYP/r0VswrKogcuTWaavs/TSbtav9VV9AIejbOCpXHCIrDK5cYWgj1sb08uWYQkbS4rZ0Gw
            FpCts+Oj1R1UksIhLE2DUUixKFhJ1FxxjqqEWmLsGrBhRztfSwqlL3gj1ZMsgC+SZMl9P4Nlg8xo
            kwvmN/kpi7ZtE8h/ZzutjYJrp55rsDSC4AhE4WYYMqUvgATbd+Lgyfi4wuKAQm2Ud+g0xcrV/JP+
            Qb0YXowjtRXgo6HyRmtQ1Mf/3JrySA94jIz5H6PoyL1BdPUUfjknnsILgW96V/JuTacczud00M7S
            Vu6qnsdXa0ribE6JV9jd/3qVveZehA8+XPYOAAD//wMAUEsDBBQABgAIAAAAIQDXg9s8ZQIAAIkG
            AAARAAAAd29yZC9kb2N1bWVudC54bWykVU1v2zAMvQ/YfzB0T2wnbZoadQos7YoeBgTNeh4UWbaF
            WKIgKfG6Xz/KX8mWokjbk2yRfHyPEqmb29+yCvbcWAEqJfE4IgFXDDKhipQ8//w+mpPAOqoyWoHi
            KXnhltwuvn65qZMM2E5y5QKEUDapNUtJ6ZxOwtCykktqx1IwAxZyN2YgQ8hzwXhYg8nCSRRHzZc2
            wLi1mG9J1Z5a0sHJUzTQXGGuHIykzo7BFKGkZrvTI0TX1ImNqIR7Qexo1sNASnZGJR2h0UDIhyQt
            oW7pI8yJilfytpF3XQWajKHhFXIAZUuhDzI+ioYSy57S/i0Re1n1frWOL07yDZLPOYM7Q2s8igPg
            CdwrxcjaIFm1dfDnezjV/xHj6C0x3Yl4iIHDORT+zdkzkVSoAeZjpTkuLnbEZ+73g4GdHuho8Tm0
            R7UdsHxjvoNZNGs671iafRfASeuuS6o5CSRLHgsFhm4qZFTHF4G/kWSBw2ID2YtfdVAnOGyyp5RE
            0f1ysry8Jv3WClsPW3dyNVveD5t3PKe7yh1ZGpiV8Ytpl4qqAkH2tEoJV6PnNQkXN2FnxlV33ueG
            1IlbxB7AtTA+bgOw9dNm7ahxmExkSMmzVFSi2F8P8I2yrU988L1X2eDZMtLebDlzK4OWswrhI3Sx
            /oP+NU7o+NoPtzop8Xs2n87bjLr4QT2iA+19phfexYiixMLNLxueG3AO5MFa8RyN8VUUN3CcZhzr
            fxXhwK+THMAd/RY71/xGbTYGlUUnqylD6T6kkY0PwoMRXnIlFF8Jx5DkdNYEYTFb2U1F29uAe/0b
            svgLAAD//wMAUEsDBBQABgAIAAAAIQClXn0txwYAANcbAAAVAAAAd29yZC90aGVtZS90aGVtZTEu
            eG1s7FnPbhtFGL8j8Q6jvbexEyeNozpV7NgNtGmj2C3qcbwe704zu7OaGSf1rUqPSCBEQRyoBFw4
            ICBSi7i07+A+Q6AIitRX4JuZ3fVOvKFJG0EFzSHenf19///MN7sXL92JGNolQlIeN7zq+YqHSOzz
            AY2Dhnej1zm37CGpcDzAjMek4Y2J9C6tvvvORbyiQhIRBPSxXMENL1QqWZmbkz4sY3meJySGZ0Mu
            IqzgVgRzA4H3gG/E5uYrlaW5CNPYQzGOgO3km8lPk8eTA3R9OKQ+8VYz/m0GQmIl9YLPRFdzJxnR
            10/3JweTJ5NHk4Ond+H6Cfx+bGgHO1VNIceyxQTaxazhgegB3+uRO8pDDEsFDxpexfx5c6sX5/BK
            SsTUMbQFuo75S+lSgsHOvJEpgn4utNqp1S+s5/wNgKlZXLvdbrWrOT8DwL4PlltdijxrneVqM+NZ
            ANnLWd6tymKl5uIL/BdmdK43m83FeqqLZWpA9rI2g1+uLNXW5h28AVn84gy+1lxrtZYcvAFZ/NIM
            vnOhvlRz8QYUMhrvzKB1QDudlHsOGXK2UQpfBvhyJYVPUZANebZpEUMeq5PmXoRvc9EBAk3IsKIx
            UuOEDLEPid7CUV9QrAXiFYILT+ySL2eWtGwkfUET1fDeTzAUzZTfi8ffv3j8EB3uPzrc//nw3r3D
            /R8tI4dqA8dBker5t5/8+eAu+uPhV8/vf1aOl0X8rz98+MuTT8uBUE5TdZ59fvDbo4NnX3z0+3f3
            S+BrAveL8B6NiETXyB7a5hEYZrziak764nQUvRDTIsVaHEgcYy2lhH9bhQ762hizNDqOHk3ievCm
            gHZSBrw8uu0o3A3FSNESyVfCyAFucs6aXJR64YqWVXBzbxQH5cLFqIjbxni3THYLx05826ME+mqW
            lo7hrZA4am4xHCsckJgopJ/xHUJKrLtFqePXTeoLLvlQoVsUNTEtdUmP9p1smhJt0AjiMi6zGeLt
            +GbzJmpyVmb1Otl1kVAVmJUo3yPMceNlPFI4KmPZwxErOvwqVmGZkt2x8Iu4tlQQ6YAwjtoDImUZ
            zXUB9haCfgVDBysN+yYbRy5SKLpTxvMq5ryIXOc7rRBHSRm2S+OwiH1P7kCKYrTFVRl8k7sVou8h
            Djg+Ntw3KXHC/fJucIMGjkrTBNFPRqIklpcJd/K3O2ZDTEyrgSbv9OqIxn/XuBmFzm0lnF3jhlb5
            7MsHJXq/qS17DXavsprZONKoj8Mdbc8tLgb0ze/O63gUbxEoiNkt6m1zftucvf98cz6uns++JU+7
            MDRoPYvYwduM4dGJp/AhZayrxoxclWYQl7AXDTqwqPmYQyrJT2lJCJe6skGggwsENjRIcPUBVWE3
            xAkM8VVPMwlkyjqQKOESDpNmuZS3xsNBQNmj6KI+pNhOIrHa5AO7vKCXs7NIzsZoFZgDcCZoQTM4
            qbCFCylTsO1VhFW1UieWVjWqmSbpSMtN1i42h3hweW4aLObehCEHwWgEXl6C1wRaNBx+MCMD7Xcb
            oywsJgpnGSIZ4gFJY6Ttno1R1QQpy5UZQ7QdNhn0wfIlXitIq2u2ryHtJEEqiqsdIy6L3utEKcvg
            aZSA29FyZHGxOFmM9hpefXF+0UM+ThreEM7NcBklEHWp50rMAng/5Sth0/6lxWyqfBrNemaYWwRV
            eDVi/T5jsNMHEiHVOpahTQ3zKE0BFmtJVv/5RXDrWRlQ0o1OpsXCMiTDv6YF+NENLRkOia+KwS6s
            aN/Z27SV8pEiohsO9lCfjcQ2hvDrVAV7BlTC6w/TEfQNvLvT3jaP3OacFl3xjZnB2XXMkhCn7VaX
            aFbJFm4aUq6DuSuoB7aV6m6MO70ppuTPyJRiGv/PTNH7CbyNWBjoCPjwNllgpCul4XGhQg5dKAmp
            3xEwSJjeAdkC73/hMSQVvNM2v4Ls6l9bc5aHKWs4VKptGiBBYT9SoSBkC9qSyb6XMKume5dlyVJG
            JqMK6srEqt0nu4T1dA9c0nu7h0JIddNN0jZgcEfzz71PK6gf6CGnWG9OJ8v3XlsD//TkY4sZjHL7
            sBloMv/nKubjwXRXtfSGPNt7i4boB9Mxq5ZVBQgrbAX1tOxfUYVTbrW2Y81YPL+YKQdRnLUYFvOB
            KIF3Skj/g/2PCp/ZryN6Q+3xbeitCD5uaGaQNpDV5+zggXSDtIt9GJzsok0mzcq6Nh2dtNeyzfqM
            J91c7hFna81OEu9TOjsfzlxxTi2epbNTDzu+tmvHuhoie7REYWmYHWxMYMyXteKXL96/DYFeh28I
            I6akSSb4jiUwzNBdUwdQ/FaiIV39CwAA//8DAFBLAwQUAAYACAAAACEAKJXjuGkDAACXCAAAEQAA
            AHdvcmQvc2V0dGluZ3MueG1stFbbbts4EH0vsP8g6HkdSY7jBGqcYuustyni7SJKP4CSaJsIbxhS
            Vtyv75AUowZxgqLFPpmaM1eemaEvPzwKnuwpGKbkIi1O8jShslEtk9tF+vV+NblIE2OJbAlXki7S
            AzXph6s/3l32paHWoppJ0IU0pWgW6c5aXWaZaXZUEHOiNJUIbhQIYvETtpkg8NDpSaOEJpbVjDN7
            yKZ5Pk8HN2qRdiDLwcVEsAaUURvrTEq12bCGDj/RAn4mbrC8Vk0nqLQ+YgaUYw5Kmh3TJnoTv+oN
            S9xFJ/u3itgLHvX6In9Lcyi3V9A+WfxMes5Ag2qoMUiQ4KFcQZh8clPMXjh6uuoTvOosxM6cKzQv
            cn8aMzf8hf0RtgOLt6wGAoFmbACXhWjKm61UQGqOTdUXs/QKO+qbUiLpS02hQZKwHfM8zRzQ0g3p
            uL0ndWWVRpU9wfjn+UWAmx0B0lgKlSYNVrxU0oLiUa9V/yq7xI4DvJDBwvefcx06sQq9jBaSCMwo
            SIf+XKuWpgh1wF4U/eqlOQOfJdbmazgeSOHsAWsplsZpZQ+crjD5in2jf8n2c2csw473XfobGbyV
            AJUu8hec1PuDpitKbIfX9D8F80ysONNrBqDgRrbI8+8GyyKJjk5cZK2JhzulbKQhz2fFfHWxDHfh
            1EakmJ+fTz8eQ163Obs+ned/H7OZT8/nS49gZkM+onTr4T+4ugwnR3IiQoMsiaiBkWTtFgi2iihr
            ePjIZMRriguU/ohUXR3BySQARhDOVzgFEfCTI8qWGX1NN94tXxPYjn4HDTgqxYn7/OTLTSOFf0B1
            OkTrgehAXgxXzGaDPybtLRNRbrq6ilYSl8APUCfbL3twDrPxevrS4tvhh+CWyG3kCLrJ3Venilxz
            qNz7QtdEaxx2VKm3xSLlbLuzhWtci18tvjP+o95OB2zqMfxymP8gjasMtYeDUwhH1BoOo+w0yk5H
            GW7RoDcbZWdRdjbK5lGG71xf7nDSgDP5gOskHp18ozhXPW0/ReEifSEKl2B2RFPk1W1FbHdVesGw
            Jk2yL+kj7k/aMovPt2atII9unU7nznzQ5uSgOvtM12FOWT+TJi2xBM09Vc+MkTr8H/A8F7etG4bt
            WB1EPS7hP0PinBlbUY372irAkv2KfO89j/8orr4DAAD//wMAUEsDBBQABgAIAAAAIQAXoBZOAgEA
            AKwBAAAUAAAAd29yZC93ZWJTZXR0aW5ncy54bWyM0MFKAzEQBuC74DssubfZlSKydLcgUvEigvoA
            aXZ2G8xkwkxqrE9v2qogXnrLJJmPmX+5+kBfvQOLo9CpZl6rCoKlwYWpU68v69mNqiSZMBhPATq1
            B1Gr/vJimdsMm2dIqfyUqihBWrSd2qYUW63FbgGNzClCKI8jMZpUSp40Gn7bxZkljCa5jfMu7fVV
            XV+rb4bPUWgcnYU7sjuEkI79msEXkYJsXZQfLZ+jZeIhMlkQKfugP3loXPhlmsU/CJ1lEhrTvCyj
            TxPpA1Xam/p4Qq8qtO3DFIjNxpcEc7NQfYmPYnLoPmFNfMuUBVgfro33lJ8e70uh/2TcfwEAAP//
            AwBQSwMEFAAGAAgAAAAhAHsMgIm0BwAAOj0AABoAAAB3b3JkL3N0eWxlc1dpdGhFZmZlY3RzLnht
            bLSbbVPbOBDH39/MfQeP30MeoOTKNO1Q6AMztEcJzL1WbIVosC2fHwjcp7+VZCvGjuPd2H1V4lj7
            29Wu/iuo9OHTSxg4zzxJhYzm7uR47Do88qQvose5+3D/9egv10kzFvkskBGfu688dT99/POPD5vz
            NHsNeOqAgSg938Te3F1nWXw+GqXemocsPQ6Fl8hUrrJjT4YjuVoJj482MvFH0/FkrH+KE+nxNAXa
            JYueWeoW5sKmNRnzCFgrmYQsS49l8jgKWfKUx0dgPWaZWIpAZK9ge3xWmpFzN0+i88KhI+uQGnJu
            HCr+KUckjSh2cM3IK+nlIY8yTRwlPAAfZJSuRbwN41BrEOK6dOl5XxDPYVC+t4knpw2eDRmTg6uE
            bSAVW4MNczsmwzeDwsDMg8rvNqt1i5PxvmCKjCgT1geMC2+ZpSchE5E1c9jUVCcX1kOf+v6WyDy2
            7sSin7Xr6MnaUsuS4Nn4TK+8amgpyUBj6S7WLOauE3rn14+RTNgyAI82k1NHVaT7EaTCl94VX7E8
            yFL1MblNio/FJ/3PVxllqbM5Z6knxD1ICFgJBRj8fhGlwoVvOEuzi1SwnV+u1Vs7v/HSrGLts/CF
            O1LE9D+w+cyCuTudlk8ulQdvngUseiyfJfnR3UPVk7nLo6OHhXq0BLtzlyVHiwtlbKTDLP+thBu/
            CR4+aVdi5sHKAzNslXEQIVAxZTQQKrvTGSia+XCXq8lleSYLiDYAsKpZ+FibcdAmUKqFUWz4lq9u
            pPfE/UUGX8xdzYKHD9e3iZAJyOjcff9eMeHhgofiu/B9rhpE8ewhWguf/7Pm0UPK/e3zX1+1PBcW
            PZlHGbh/NtNVEKT+lxePx0omwXTEVIZ/qgGgYZCOCkc7lIutN+ZBjaof/lsiJyaHOylrzlRLc7T/
            e0E66rw3aKoiqgag7ZJ8Pelv4rS/iXf9Teji7TcXs/5ewEamb0ZMbVSqEp/UTHqm+KrzcPJ+T8mq
            EY0q6hzRKJrOEY0a6RzRKInOEY0K6BzRSHjniEZ+O0c00rl3hMe0cNWr6ETPBmph34ss4Gr8XgGa
            9JS6otU4tyxhjwmL145qrHW394nlIl9mOFe1nB4ulosskWq72TEj0J3V0j1Yk7+E8ZqlAnblXaCe
            U3+vtj7Ot0TA9rUD9c4UXyMmvTHZ2cJuA+bxtQx8njj3/MVklDD+p3QWZpfR6VzPtN6Ix3XmwK5Q
            tdxO2FnLpLfPhLF/I1I9B3sX01lLKF3GUTk8a6nLduM/uC/ysJwaxG7kzOg5Ic01hHZx/xSdqhQ1
            V1dnFCoBmBBMu6CHoO0j/DfNhW5f5Rjjv2lFB9pH+G8a14H2dX3szy9Zaa7gzyoOannNyGv3UgYy
            WeVBuQY65WFGXsEWgQuBvIitfZRIzMgr+I18OheeB7+5YeqUnIutjhIo5HQYil5s+FjISanJ3oQQ
            ETlBNdaUwOqntQQQWXTv+LNQfwSmNgOt0nav2bmcT1pmAFoQag/9K5dZ9x562qJ5WMp1BH8uSbmD
            o520rDwsragn0+8IOe7X+Aigfh2QAOrXCgmglvpo3/PYnoiH9G+OBBZZlm0X02WHVuYZWZktiNYC
            BuqbiP1Xy+ptr4Vm30RQyAlq9k0EhZydWi+zfRPBGqxvIlgtXaM9R1VNpQRF7ptVkN0JICIaRrwR
            oGHEGwEaRrwRoP7i3Q0ZTrwRLLI2WE2tijcCpF+h/KpvQVXxRoDI2mDUrvibUdn3tJX9v9wOIN4I
            CjlBTfFGUMjZaRNvBEu/QqmEGstKHYI1jHgjQMOINwI0jHgjQMOINwI0jHgjQP3FuxsynHgjWGRt
            sJpaFW8EiCwPFlQVbwRIv0LRhp3irVf9bxdvBIWcoKZ4Iyjk7NQE1W5SESxygmosK94Iln6FUgwF
            Sxc3JahhxBsR0TDijQANI94I0DDijQD1F+9uyHDijWCRtcFqalW8ESCyPFhQVbwRILI27BRvvRh/
            u3gjKOQENcUbQSFnpyaoVucQLHKCaiwr3giWrpfe4o0A6VcOBVEiGka8ERENI94I0DDijQD1F+9u
            yHDijWCRtcFqalW8ESCyPFhQVbwRILI27BRvvUZ+u3gjKOQENcUbQSFnpyaoVrwRLHKCaiwrdQjW
            MOKNAOnC7C3eCJB+5QCQXkWUNA0j3oiIhhFvBKi/eHdDhhNvBIusDVZTq+KNAJHlwYKq4o0AkbVB
            nbOF86Lo46mTliLAnjMoTzWggdOWJGGBRYB3fMUTuFXIu0+H9ASWERKILeWBDfGzlE8O7mD3SUuB
            oFFiGQipj3S/6lM6lYsIJ7M9Nwnu/750vpsLMI1xuqTenryB20PV60L6epK6OAR+Zq8xXNmJy5Pl
            yhpcEFL3uoorQPpO6DVcCGL6xo+64gPv6PtUxUUf/V+2BRB+Bpge06R4a8B4cBlqH2XcwLQcf9fY
            7d2L0qniGPx2s2Tee3MYc6+XmTryvc/DScNDMxGOPixustb0Cy5faU+6HIOULANzhQx+uI58CGxT
            3L4yyfJfmDEF31/yIPjBEjXXmYzbXw34KjPfTsa6w9VMLWWWybB9fKIPgGtPdhmAnFedMR9VEO3F
            EOXhkifFcfK2kpvumGpzjrUl+9hZ3vpV/pR+/B8AAP//AwBQSwMEFAAGAAgAAAAhALKCYC+CAQAA
            EQMAABEACAFkb2NQcm9wcy9jb3JlLnhtbCCiBAEooAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
            AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
            AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
            AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
            AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
            AAAAAJyS30/CMBDH3038H5a+b92AqFnGMGp4ksREjMa32h5QWX+kPZj893YbDIgmJr717r73uV8t
            Jl+qirbgvDR6TLIkJRFoboTUyzF5mU/jGxJ5ZFqwymgYkx14MikvLwpuc24cPDljwaEEHwWS9jm3
            Y7JCtDmlnq9AMZ8EhQ7BhXGKYTDdklrG12wJdJCmV1QBMsGQ0QYY255I9kjBe6TduKoFCE6hAgUa
            Pc2SjB61CE75XxPayIlSSdzZMNO+3VO24F2wV3952Qvruk7qYdtG6D+jb7PH53bUWOpmVxxIWQie
            o8QKyoIen+HlNx+fwLFz90YIcAcMjSuXRvMVcwkCSqbZrRWLhawqcAk3qoUdlM0N1rCrjRM+8M6s
            ABTguZMWw2W7ameOoK6Yx1k49UKCuNv9VfhnQlPfwVY2f6cctg30Zpi/XXc3FogoLDDv1n2IvA7v
            H+ZTUg7S7DpOB3E2mmejPEvzNH1v5jzLbxbaOdS+438TD4BuZeefuPwGAAD//wMAUEsDBBQABgAI
            AAAAIQAdJ5EkMwcAAEk6AAAPAAAAd29yZC9zdHlsZXMueG1stJvfU9s4EMffb+b+B4/faUjCkSvT
            tENpe2Wm7VECc8+KrRBNbctnKwXur7/VyjHGju1d7D4R/9B+tNrVd5UgvXn3EEfeT5nlSidLf/rq
            2PdkEuhQJXdL//bm09GfvpcbkYQi0olc+o8y99+9/f23N/dnuXmMZO6BgSQ/i4OlvzUmPZtM8mAr
            Y5G/0qlM4OFGZ7EwcJndTWKR/dilR4GOU2HUWkXKPE5mx8enfmEmo1jRm40K5Acd7GKZGGw/yWQE
            FnWSb1Wa763dU6zd6yxMMx3IPAen48jZi4VKSjPTk4ahWAWZzvXGvAJnJq5HE2sKmk+P8VMc+V4c
            nF3eJToT6wgG73564r+FkQt18EFuxC4yub3MrrLisrjCP590YnLv/kzkgVI3MKRgIFZg6/N5kisf
            nkiRm/NciYMPt/atg0+C3FSsvVeh8ieWmP8HNn+KaOnPZvs7F7YHz+5FIrnb38t2R9e31Z4sfZkc
            3a7srTXYXfoiO1qdW2MTdHP/t+Ju+sx5uMKupCKAYIAZsTESkgJyxBqNlM3B2QLyxV1c7+y4ip3R
            BQQNAKxqFi5rIw65ApmzcgkMT+Xmiw5+yHBl4MHSRxbcvL28ypTOIEmX/uvXlgk3VzJWn1UYSjtf
            inu3yVaF8p+tTG5zGT7d//4Jk7+wGOhdYqD7pwvMgigPPz4EMrVpC6YTYSP8zTaAxIFwVDjYoZ16
            6o27UaPizX/3yKmL4UHKVgo7wz3sfycIvd4NBs2sR1UH0C6rr/PhJk6Gm/hjuAlM3mFjsRjeC9D1
            oRFxuVHJSnpQjQ5c8lXHYf66I2Vti0YW9bZoJE1vi0aO9LZopERvi0YG9LZoBLy3RSO+vS0a4exs
            EQgUrnoWzXE0SBP7RplI2vadAjQdKHVFqfGuRCbuMpFuPVtY693uEsvVbm1oXUU5fblYrkymk7ve
            EYHqbKfuizX5Y5xuRa5gldQz9LOBQ39jVz3eX5kKe1F/uORr+IQLk4Ml7CoSgdzqKJSZdyMfXEQZ
            7b9pb+VWGb2dGxjWL+pua7zVFktuL+y0ZdDbR8LZ/6JyHIPOyXTa4kqfcVIMT1vyst34VxmqXbwf
            GsJq5NTpOSPMNQR2sXuITmyImrOr1wsbAIoLrlzwXUD7hP674sK3b2NM6b8rRS+0T+i/K1wvtI/5
            0R1fttJ8gC+tHml6Ldhz90JHOtvsov0c6JWHBXsGlwiaC+xJXNonicSCPYOfyad3HgTwzY2Sp+xY
            POkog8IOh6PgZKP7wg5KTfamDI/YAaqxZgzWMK1lgNiiey1/KvubGLcYoEqXa83e6TxvGQEoQaQ1
            9PedNv1r6FmL5lEplwn8XJJLj0abt8w8Kq3IJ1fvGDEeVvgYoGEVkAEaVgoZoJb8aF/zlDWRDhle
            HBkstiyXVQzTjqzMC7YylyBeCRipbhLWXy2ztz0XmnWTQGEHqFk3CRR2dGq1rKybBNZodZPAaqka
            7TGqairHKXbdrILKlQDBo3HEmwAaR7wJoHHEmwAaLt79kPHEm8Bia0OpqVXxJoDwFc5X/RJUFW8C
            iK0NTu2K34z2dQ+tdH+5HUG8CRR2gJriTaCwo9Mm3gQWvsLJhBqrlDoCaxzxJoDGEW8CaBzxJoDG
            EW8CaBzxJoCGi3c/ZDzxJrDY2lBqalW8CSC2PJSgqngTQPgKRxsOijfO+l8u3gQKO0BN8SZQ2NGp
            CWq5SCWw2AGqsUrxJrDwFU4yFCxMbo5T44g3waNxxJsAGke8CaBxxJsAGi7e/ZDxxJvAYmtDqalV
            8SaA2PJQgqriTQCxteGgeONk/OXiTaCwA9QUbwKFHZ2aoJY6R2CxA1RjleJNYGG+DBZvAghfeSmI
            49E44k3waBzxJoDGEW8CaLh490PGE28Ci60NpaZWxZsAYstDCaqKNwHE1oaD4o1z5JeLN4HCDlBT
            vAkUdnRqglqKN4HFDlCNVUodgTWOeBNAmJiDxZsAwldeAMJZxAnTOOJN8Ggc8SaAhot3P2Q88Saw
            2NpQampVvAkgtjyUoKp4E0BsbbD7bGG/KHl76rQlCaj7DPa7GsjAWUuQqMDCwWu5kRkcspL9u0MG
            AvceMogt6UF18b3WPzzaxu55S4KQUWodKY1buh9xl07lIMJ80XGS4ObvC++zOwDTaIcp9XznDZwe
            qh4XwuNJ9uAQ9NM8pnBkJ93vLLfW4ICQPddVHAHCI3KXcCBI4Ikfe8QH3sHzVMVBH/yXbQGEzwDD
            Nk1KsAVMAIehuijHDUzL9nfEPp292Heq2Ab/tFhy7z3bjNnZS2O3fHf1cNrooRsIDzeLu6g1+wWH
            r7AnfR2DkKwjd4QMPlwmITgGhwDxv2IuWOGDcKbg+YWMoq8is2NtdNr+aiQ3xj2dHmOFq5laa2N0
            3N4+ww3g2JNDBiDm1c64S+tEezIku3gtMzjB1TXUswND7faxtkSfOspP/dp/yt/+DwAA//8DAFBL
            AwQUAAYACAAAACEAw8lVYcIBAACiBAAAEgAAAHdvcmQvZm9udFRhYmxlLnhtbLySy27bMBBF9wX6
            DwL3MSlZzkOIHLRuDHTTRZF+AE1TFlE+BA5t1X/fISk7RYMEcReVAEK6w7kaHt37h19GFwfpQTnb
            knLGSCGtcFtldy358bS+uiUFBG63XDsrW3KUQB6WHz/cj03nbIAC+y00RrSkD2FoKAXRS8Nh5gZp
            sdg5b3jAV7+jhvuf++FKODPwoDZKq3CkFWPXZLLx73FxXaeE/OLE3kgbUj/1UqOjs9CrAU5u43vc
            Rue3g3dCAuCZjc5+hit7tinrF0ZGCe/AdWGGh6F5IhqtsL1k6cloUhjRfN1Z5/lGI7uxrMlyAleM
            jeUGxRXXauNVKgzcOpAl1g5ct4RVbM0WuMa7ZvO4EhodRM89yHDauFplueNG6eNJhVEB5MKgguhP
            +oF7FQfKJVA7LOxhw1ryyBirPq3XJCslTheV+ubzpFQ4VL7uJmV+VjA5OFjySVvK7IMK+kxdLH6T
            5ui8IPGkjITimxyL785w+wqRil0jiQXyiGTmFxHxyTcRvITI499Ebm4X/4XIihuMBn+FRCSQSUQi
            l2Xj30iw6k8Sdfyp9Vl5zkZKAibqjWzcpYy9kY0pJLD8DQAA//8DAFBLAwQUAAYACAAAACEA1hJD
            dWwBAADAAgAAEAAIAWRvY1Byb3BzL2FwcC54bWwgogQBKKAAAQAAAAAAAAAAAAAAAAAAAAAAAAAA
            AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
            AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
            AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
            AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
            AAAAAAAAAACcUk1PwzAMvSPxH6reWTqEEJq8IDSEOPAxqYWdo9RtI9IkSgLa/j3OSrsibuRkP9sv
            zy+B232vsy/0QVmzzpeLIs/QSFsr067zt+rh4ibPQhSmFtoaXOcHDPktPz+DrbcOfVQYMqIwYZ13
            MboVY0F22IuwoLKhSmN9LyKlvmW2aZTEeys/ezSRXRbFNcN9RFNjfeEmwnxgXH3F/5LWViZ94b06
            OBLMocLeaRGRvyQ5GtgEQGWj0JXqkRcETwlsRYuBL4ENAeysr0PqGQLYdMILGcm61DTL4M45raSI
            ZCl/VtLbYJuYvR6Xz9I0sHkLkCElyk+v4iHxz1N4UmZQMQSkyovWC9f9SJsyKKXQuKGteSN0QGAn
            ADa2d8IcOOkcI+L7CG+usvfJlp+R3+BsxZ2KXemEHLSclp3hUJIhWJP6ke0EwCO9g9fpSpo1LdZj
            z99Csu99+JB8ebUo6Bz9GjF6kOmn8G8AAAD//wMAUEsBAi0AFAAGAAgAAAAhAAkkh4KBAQAAjgUA
            ABMAAAAAAAAAAAAAAAAAAAAAAFtDb250ZW50X1R5cGVzXS54bWxQSwECLQAUAAYACAAAACEAHpEa
            t/MAAABOAgAACwAAAAAAAAAAAAAAAAC6AwAAX3JlbHMvLnJlbHNQSwECLQAUAAYACAAAACEAfDuX
            OSIBAAC5AwAAHAAAAAAAAAAAAAAAAADeBgAAd29yZC9fcmVscy9kb2N1bWVudC54bWwucmVsc1BL
            AQItABQABgAIAAAAIQDXg9s8ZQIAAIkGAAARAAAAAAAAAAAAAAAAAEIJAAB3b3JkL2RvY3VtZW50
            LnhtbFBLAQItABQABgAIAAAAIQClXn0txwYAANcbAAAVAAAAAAAAAAAAAAAAANYLAAB3b3JkL3Ro
            ZW1lL3RoZW1lMS54bWxQSwECLQAUAAYACAAAACEAKJXjuGkDAACXCAAAEQAAAAAAAAAAAAAAAADQ
            EgAAd29yZC9zZXR0aW5ncy54bWxQSwECLQAUAAYACAAAACEAF6AWTgIBAACsAQAAFAAAAAAAAAAA
            AAAAAABoFgAAd29yZC93ZWJTZXR0aW5ncy54bWxQSwECLQAUAAYACAAAACEAewyAibQHAAA6PQAA
            GgAAAAAAAAAAAAAAAACcFwAAd29yZC9zdHlsZXNXaXRoRWZmZWN0cy54bWxQSwECLQAUAAYACAAA
            ACEAsoJgL4IBAAARAwAAEQAAAAAAAAAAAAAAAACIHwAAZG9jUHJvcHMvY29yZS54bWxQSwECLQAU
            AAYACAAAACEAHSeRJDMHAABJOgAADwAAAAAAAAAAAAAAAABBIgAAd29yZC9zdHlsZXMueG1sUEsB
            Ai0AFAAGAAgAAAAhAMPJVWHCAQAAogQAABIAAAAAAAAAAAAAAAAAoSkAAHdvcmQvZm9udFRhYmxl
            LnhtbFBLAQItABQABgAIAAAAIQDWEkN1bAEAAMACAAAQAAAAAAAAAAAAAAAAAJMrAABkb2NQcm9w
            cy9hcHAueG1sUEsFBgAAAAAMAAwACQMAADUuAAAAAA==
            --{boundary value}
            Content-Disposition: form-data; name='folder_id'
              
            0
            --{boundary value}--       
          
      
+ Response 200 (application/json)

    Success - information about new document template

    + Attributes (Template_info)
  
+ Response 400 (application/json)

    Bad request - request validation error

    + Attributes (Error_response)
    
+ Response 401 (application/json)

    Unauthorized - access application is invalid or doesn't have access privileges to requested resource

    + Attributes (Error_response)

+ Response 403 (application/json)

    403 Forbidden - Access to this resource on the server is denied

    + Attributes (Error_response)

+ Response 500 (application/json)

    The server encountered an unexpected condition which prevented it from fulfilling the request

    + Attributes (Error_response)
    
### Creates a new document template by uploading file from URL [POST /v2/templates]
+ Request (application/json)
    
    + Headers
    
            Authorization: Bearer

    + Attributes
        + file (string, required)
        + folderid (number, optional) - Filter by folder
            + Default: 0
      
    + Body

           {
               "file":"http:\/\/www.adobe.com\/content\/dam\/Adobe\/en\/devnet\/acrobat\/pdfs\/pdf_open_parameters.pdf", 
               "folderid": 0
           }
    
+ Response 200 (application/json)

    Success - information about new document template

    + Attributes (Template_info)
  
+ Response 400 (application/json)

    Bad request - request validation error

    + Attributes (Error_response)
    
+ Response 401 (application/json)

    Unauthorized - access application is invalid or doesn't have access privileges to requested resource

    + Attributes (Error_response)

+ Response 403 (application/json)

    403 Forbidden - Access to this resource on the server is denied

    + Attributes (Error_response)

+ Response 500 (application/json)

    The server encountered an unexpected condition which prevented it from fulfilling the request

    + Attributes (Error_response)
    
### Information about created template [GET /v2/templates/{template_id}]
+ Request 
    
    + Headers
    
            Authorization: Bearer

+ Parameters
    + template_id: 1023456789 (number, required) - Id of a template.
      
+ Response 200 (application/json)

    Success - Information about created document template

    + Attributes (Template_info)
     
+ Response 401 (application/json)

    User authentication error

    + Attributes (Error_response)

+ Response 403 (application/json)

    403 Forbidden - Access to this resource on the server is denied

    + Attributes (Error_response)

+ Response 404 (application/json)

    The server has not found anything matching the Request-URI

    + Attributes (Error_response)
    
+ Response 500 (application/json)

    The server encountered an unexpected condition which prevented it from fulfilling the request

    + Attributes (Error_response)

### Updates template information [PUT /v2/templates/{template_id}]
+ Request (application/json)
    
    + Headers
    
            Authorization: Bearer
            
    + Body

            {
                "name": "pdf_file_name"
                "folder_id": 0
            }
        
+ Parameters
    + template_id: 1023456789 (number, required) - Id of a template.
    
+ Attributes
    + name  (string, optional)
    + folder_id (number, optional)
        + Default: 0
        
+ Response 200 (application/json)

    Success - Information about updated document template

    + Attributes (Template_info)
     
+ Response 401 (application/json)

    User authentication error

    + Attributes (Error_response)

+ Response 403 (application/json)

    403 Forbidden - Access to this resource on the server is denied

    + Attributes (Error_response)

+ Response 404 (application/json)

    The server has not found anything matching the Request-URI

    + Attributes (Error_response)
    
+ Response 500 (application/json)

    The server encountered an unexpected condition which prevented it from fulfilling the request

    + Attributes (Error_response)

###  Fillable fields for selected document template [GET /v2/templates/{template_id}/dictionary]
+ Request 
    
    + Headers
    
            Authorization: Bearer

+ Parameters
    + template_id: 1023456789 (number, required) - Id of a template.
      
+ Response 200 (application/json; charset=utf-8)

    Success 

    + Attributes (array[Fillable_template_field])
     
+ Response 401 (application/json)

    User authentication error

    + Attributes (Error_response)

+ Response 403 (application/json)

    403 Forbidden - Access to this resource on the server is denied

    + Attributes (Error_response)

+ Response 404 (application/json)

    The server has not found anything matching the Request-URI

    + Attributes (Error_response)
    
+ Response 500 (application/json)

    The server encountered an unexpected condition which prevented it from fulfilling the request

    + Attributes (Error_response)

### Downloads document template [GET /v2/templates/{template_id}/download]
+ Request 
    
    + Headers
    
            Authorization: Bearer

+ Parameters
    + template_id: 1023456789 (number, required) - Id of a template.
      
+ Response 200

        Success. PDF file to download
         
+ Response 401 (application/json)

    User authentication error

    + Attributes (Error_response)

+ Response 403 (application/json)

    403 Forbidden - Access to this resource on the server is denied

    + Attributes (Error_response)

+ Response 404 (application/json)

    The server has not found anything matching the Request-URI

    + Attributes (Error_response)
    
+ Response 500 (application/json)

    The server encountered an unexpected condition which prevented it from fulfilling the request

    + Attributes (Error_response)

### Child documents for selected document template [GET /v2/templates/{template_id}/filled_documents]
+ Request

    + Headers

            Authorization: Bearer

+ Parameters
    + template_id: 1023456789 (number, required) - Id of a template.

+ Response 200 (application/json)

    Success - Information about child template

    + Attributes
        + items (array[Filled_document_response])
        + `total`(number)
            + Default: 1
        + `current_page`(number)
            + Default: 1
        + `per_page` (number)
            + Default: 15
        + `prev_page_url` (string)
            + Default: `empty string`
        + `next_page_url` (string)
            + Default: `empty string`

+ Response 401 (application/json)

    User authentication error

    + Attributes (Error_response)

+ Response 403 (application/json)

    403 Forbidden - Access to this resource on the server is denied

    + Attributes (Error_response)

+ Response 404 (application/json)

    The server has not found anything matching the Request-URI

    + Attributes (Error_response)

+ Response 500 (application/json)

    The server encountered an unexpected condition which prevented it from fulfilling the request

    + Attributes (Error_response)

### Downloads zip archive of signatures [GET /v2/templates/{template_id}/download_signatures]
+ Request 
    
    + Headers
    
            Authorization: Bearer

+ Parameters
    + template_id: 1023456789 (number, required) - Id of a template.
      
+ Response 200

        Success. Zip archive to download
         
+ Response 401 (application/json)

    User authentication error

    + Attributes (Error_response)

+ Response 403 (application/json)

    403 Forbidden - Access to this resource on the server is denied

    + Attributes (Error_response)

+ Response 404 (application/json)

    The server has not found anything matching the Request-URI

    + Attributes (Error_response)
    
+ Response 500 (application/json)

    The server encountered an unexpected condition which prevented it from fulfilling the request

    + Attributes (Error_response)
    
### Fills a fillable form template [POST /v2/templates/{template_id}/fill]
+ Request (application/json)
    
    + Headers
    
            Authorization: Bearer
    + Body
        
            {
                "template_id": 0,
                "fillable_fields": {
                    "key1": "Some_key",
                    "key2": "Some_other_key"
                }
            }
            
+ Parameters
    + template_id: 1023456789 (number, required) - Id of a template.
    
+ Attributes
    + `fillable_fields` (Fillable_fields)

+ Response 200 (application/json)

    Success - filled the form template

    + Attributes (Fillable_template)
  
+ Response 400 (application/json)

    Bad request - request validation error

    + Attributes (Error_response)
    
+ Response 401 (application/json)

    Unauthorized - access application is invalid or doesn't have access privileges to requested resource

    + Attributes (Error_response)

+ Response 403 (application/json)

    403 Forbidden - Access to this resource on the server is denied

    + Attributes (Error_response)

+ Response 500 (application/json)

    The server encountered an unexpected condition which prevented it from fulfilling the request

    + Attributes (Error_response)

### Uploading the initial version of the document [GET /v2/templates/{template_id}/original_document]
+ Request 

    + Headers

            Authorization: Bearer

+ Parameters
    + template_id: 1023456789 (number, required) - Id of a template.

+ Response 200

        Success - Uploading the initial version of the document

+ Response 400 (application/json)

    Bad request - request validation error

    + Attributes (Error_response)

+ Response 401 (application/json)

    Unauthorized - access application is invalid or doesn't have access privileges to requested resource

    + Attributes (Error_response)

+ Response 403 (application/json)

    403 Forbidden - Access to this resource on the server is denied

    + Attributes (Error_response)

+ Response 500 (application/json)

    The server encountered an unexpected condition which prevented it from fulfilling the request

    + Attributes (Error_response)

### Get values for fillable form [GET /v2/templates/{template_id}/values]
+ Request

    + Headers

            Authorization: Bearer

+ Parameters
    + template_id: 1023456789 (number, required) - Id of a template.

+ Response 200 (application/json)

    Success - Get values for fillable form

    + Attributes (array[Template_values])

+ Response 400 (application/json)

    Bad request - request validation error

    + Attributes (Error_response)

+ Response 401 (application/json)

    Unauthorized - access application is invalid or doesn't have access privileges to requested resource

    + Attributes (Error_response)

+ Response 403 (application/json)

    403 Forbidden - Access to this resource on the server is denied

    + Attributes (Error_response)

+ Response 500 (application/json)

    The server encountered an unexpected condition which prevented it from fulfilling the request

    + Attributes (Error_response)

### Creates a new share link to document [POST /v2/templates/{template_id}/constructor]
+ Request

    + Headers

            Authorization: Bearer

    + Attributes
        + expire (number, optional) - The number of days of life for link. Max value - 1000
            + Default: 5

+ Parameters
    + template_id: 1023456789 (number, required) - Id of a template.

+ Response 200 (application/json)

    Success - information about new share link

    + Attributes
        + document_id: `1111111111` (number) - Template id which was shared
        + hash: `string` (string) - Hash for shared template
        + url: `some url` (string) - Permalink to edit shared template
        + short_url: `short link` (string) - Short link  to edit shared template

+ Response 400 (application/json)

    Bad request - request validation error

    + Attributes (Error_response)

+ Response 401 (application/json)

    Unauthorized - access application is invalid or doesn't have access privileges to requested resource

    + Attributes (Error_response)

+ Response 403 (application/json)

    403 Forbidden - Access to this resource on the server is denied

    + Attributes (Error_response)

+ Response 500 (application/json)

    The server encountered an unexpected condition which prevented it from fulfilling the request

    + Attributes (Error_response)

### Retrieve a list of hash [GET /v2/templates/{template_id}/constructor]
+ Request

    + Headers

            Authorization: Bearer

+ Parameters
    + template_id: 1023456789 (number, required) - Id of a template.

+ Response 200 (application/json)

    Success

    + Attributes (array[Constructor_list])

+ Response 400 (application/json)

    Bad request - request validation error

    + Attributes (Error_response)

+ Response 401 (application/json)

    Unauthorized - access application is invalid or doesn't have access privileges to requested resource

    + Attributes (Error_response)

+ Response 403 (application/json)

    403 Forbidden - Access to this resource on the server is denied

    + Attributes (Error_response)

+ Response 500 (application/json)

    The server encountered an unexpected condition which prevented it from fulfilling the request

    + Attributes (Error_response)

### Deletes one share link to document by hash [DELETE /v2/templates/{template_id}/constructor/{hash}]
+ Request

    + Headers

            Authorization: Bearer

+ Parameters
    + template_id: 1023456789 (number, required) - Id of a template
    + hash: `hash` (string, required) - Hash for shared link

+ Response 200 (application/json)

    Success - information about new share link

    + Attributes
        + message: `One URL to the documents was deleted` (string)

+ Response 400 (application/json)

    Bad request - request validation error

    + Attributes (Error_response)

+ Response 401 (application/json)

    Unauthorized - access application is invalid or doesn't have access privileges to requested resource

    + Attributes (Error_response)

+ Response 403 (application/json)

    403 Forbidden - Access to this resource on the server is denied

    + Attributes (Error_response)

+ Response 500 (application/json)

    The server encountered an unexpected condition which prevented it from fulfilling the request

    + Attributes (Error_response)

### Deletes all share links to document by id [DELETE /v2/templates/{template_id}/constructor]
+ Request

    + Headers

            Authorization: Bearer

+ Parameters
    + template_id: 1023456789 (number, required) - Id of a template.

+ Response 200 (application/json)

    Success - information about new share link

    + Attributes
        + message: `All URLs to the documents were deleted` (string)

+ Response 400 (application/json)

    Bad request - request validation error

    + Attributes (Error_response)

+ Response 401 (application/json)

    Unauthorized - access application is invalid or doesn't have access privileges to requested resource

    + Attributes (Error_response)

+ Response 403 (application/json)

    403 Forbidden - Access to this resource on the server is denied

    + Attributes (Error_response)

+ Response 500 (application/json)

    The server encountered an unexpected condition which prevented it from fulfilling the request

    + Attributes (Error_response)


### Deletes document template item [DELETE /v2/templates/{template_id}]
+ Request 
    
    + Headers
    
            Authorization: Bearer

+ Parameters
    + template_id: 1023456789 (number, required) - Id of a template.
      
+ Response 200 (application/json)

    Success 

    + Attributes (Delete_response)
     
+ Response 401 (application/json)

    User authentication error

    + Attributes (Error_response)

+ Response 403 (application/json)

    403 Forbidden - Access to this resource on the server is denied

    + Attributes (Error_response)

+ Response 404 (application/json)

    The server has not found anything matching the Request-URI

    + Attributes (Error_response)
    
+ Response 500 (application/json)

    The server encountered an unexpected condition which prevented it from fulfilling the request

    + Attributes (Error_response)




# Data Structures



## `Error_response` (object)
+ `errors`(Error_message)

## `Error_message` (object)
+ `message`: `string`(string)
+ `id`: `string`(string)


## `Delete_response` (object)
+ `total`: 0(number)
+ `message`: `string`(string)



## `Application_Response` (object)
+ `id`: `applicationId` (string)
+ `secret`: `secret` (string)
+ `name`: `app` (string)
+ `description`: `some desc+ some text` (string)
+ `domain`: `domain.com` (string)
+ `redirect_uri`: `http://domain.com` (string)
+ `embedded_client` (Application_Embedded_Client)

## `Application_Embedded_Client` (object)
+ `domain`: `domain.com` (string)
+ `allow_all_domains`: `false` (boolean)

## `Application_List` (object)
+ `items` (array[Application_Response])
+ `total`: `1` (number)
+ `current_page`: `1` (number)
+ `per_page`: `15` (number)
+ `prev_page_url`: `string` (string)
+ `next_page_url`: `string` (string)

## `Template_list` (object)
+ `items` (array[Template_info])
+ `total`: `1` (number)
+ `current_page`: `1` (number)
+ `per_page`: `15` (number)
+ `prev_page_url`: `string` (string)
+ `next_page_url`: `string` (string)

## `Template_info` (object)
+ `id`: `12345678` (number)
    + Default: 0
+ `name`: `PDF_FILE_NAME` (string)
+ `type`: `PDF` (string)
+ `created`: `1457222400` (number)
    + Default: 0
+ `folder` (Folder_info)

## `Folder_info` (object)
+ `id`: `12345678` (number)
    + Default: 0
+ `name`: `My_folder` (string)
+ `documents_count`: `15` (number)
    + Default: 0

## `Constructor_list` (object)
+ `hash`: `hash_string` (string)
+ `expiration`: `2017-01-01 00:00:00` (string) - Date of end-of-life for the link

## `Template_values` (object)
+ `Text_1`: `some_string` (string, optional)
+ `Number_1`: `12345` (number, optional)
+ `Number_2`: `67890` (number, optional)
+ `Checkbox_1`: `ON` (enum[string], optional)
    + Members
        + `ON`
        + `OFF`
+ `Date_1`: `02/07/2017` (string, optional)
+ `Dropdown_1`: `string` (string, optional)

## `Fillable_fields` (object)
+ `key1`: `Some_key` (string, optional)
+ `key2`: `Some_other_key` (string, optional)

## `Fillable_template_field` (object)
+ `type`: `PDF` (string)
+ `name`: `PDF_file_name` (string, optional)
+ `label`: `Title`(string, optional)
+ `required` (boolean)

## `Filled_document_response` (object)
+ `id`: `11111111` (number)
    + Default: 0
+ `created`: `1457222400` (number) - Timestamp of date created
    + Default: 0

## `Fillable_template` (object)
+ `id`: `87654321` (number)
    + Default: 0
+ `template_id`: `12345678` (number)
    + Default: 0