## `Application_Response` (object)
+ `id`: `applicationId` (string)
+ `secret`: `secret` (string)
+ `name`: `app` (string)
+ `description`: `some desc+ some text` (string)
+ `domain`: `domain.com` (string)
+ `redirect_uri`: `http://domain.com` (string)
+ `embedded_client` (Application_Embedded_Client)

## `Application_Embedded_Client` (object)
+ `domain`: `domain.com` (string)
+ `allow_all_domains`: `false` (boolean)

## `Application_List` (object)
+ `items` (array[Application_Response])
+ `total`: `1` (number)
+ `current_page`: `1` (number)
+ `per_page`: `15` (number)
+ `prev_page_url`: `string` (string)
+ `next_page_url`: `string` (string)
