## `Application_Response` (object)
+ `id`: `applicationId` (string)
+ `secret`: `secret` (string)
+ `name`: `app` (string)
+ `description`: `some desc+ some text` (string)
+ `domain`: `domain.com` (string)
+ `redirect_uri`: `http://domain.com` (string)
+ `embedded_client` (Application_Embedded_Client)

## `Application_Embedded_Client` (object)
+ `domain`: `domain.com` (string)
+ `allow_all_domains`: `false` (boolean)

## `Application_List` (object)
+ `items` (array[Application_Response])
+ `total`: `1` (number)
+ `current_page`: `1` (number)
+ `per_page`: `15` (number)
+ `prev_page_url`: `string` (string)
+ `next_page_url`: `string` (string)

## `Template_list` (object)
+ `items` (array[Template_info])
+ `total`: `1` (number)
+ `current_page`: `1` (number)
+ `per_page`: `15` (number)
+ `prev_page_url`: `string` (string)
+ `next_page_url`: `string` (string)

## `Template_info` (object)
+ `id`: `0` (number)
+ `name`: `PDF_FILE_NAME` (string)
+ `type`: `PDF` (string)
+ `created`: `0` (number)
+ `folder` (Folder_info)

## `Folder_info` (object)
+ `id`: `0` (number)
+ `name`: `MyFolder` (string)
+ `documents_count`: `0` (number)

## `Constructor_List` (object)
+ `hash`: `hash string` (string)
+ `expiration`: `2017-01-01 00:00:00` (string) - Date of end-of-life for the link

## `Template_Values` (object)
+ `Text_1`: `some string` (string, optional)
+ `Number_1`: `12345` (number, optional)
+ `Number_2`: `67890` (number, optional)
+ `Checkbox_1`: `ON` (enum[string], optional)
    + Members
        + `ON`
        + `OFF`
+ `Date_1`: `02/07/2017` (string, optional)
+ `Dropdown_1`: `string` (string, optional)

## `Fillable_Fields` (object)
+ `key1`: (string, optional)
    + Default: 0
+ `key2`: (string, optional)
    + Default: 0`

## `Fillable_Template_Field` (object)
+ `type`: `PDF` (string)
+ `name`: `PDF_FILE_NAME` (string, optional)
    + Default: 0
+ `label`: `Title`(string, optional)
    + Default: 0
+ `required` (boolean)

## `Filled_Document_Response` (object)
+ `id`: `11111111` (number)
+ `created`: `1457222400` (number) - Timestamp of date created