## `Error_response` (object)
+ `errors`(Error_message)

## `Error_message` (object)
+ `message`: `string`(string)
+ `id`: `string`(string)


## `Delete_response` (object)
+ `total`: 0(number)
+ `message`: `string`(string)
