## `Error_Response` (object)
+ `errors`(Error_Message)

## `Error_Message` (object)
+ `message`: `string`(string)
+ `id`: `string`(string)


## `Delete_Response` (object)
+ `total`: 0(number)
+ `message`: `string`(string)
